name: pd1
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=19.3.0
  - appmode=0.7.0
  - backcall=0.1.0
  - bleach=3.1.4
  - boost-cpp=1.72.0
  - branca=0.4.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - cairo=1.16.0
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.1
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cryptography=2.8
  - curl=7.69.1
  - cycler=0.10.0
  - cython=0.29.16
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - entrypoints=0.3
  - expat=2.2.9
  - fastparquet=0.3.3
  - fiona=1.8.13
  - folium=0.10.1
  - fontconfig=2.13.1
  - freetype=2.10.1
  - freexl=1.0.5
  - gdal=3.0.4
  - geopandas=0.7.0
  - geos=3.8.1
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.64.2
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=64.2
  - idna=2.9
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - ipykernel=5.2.0
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9c
  - json-c=0.13.1
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kealib=1.4.13
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.69.1
  - libdap4=3.20.4
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgdal=3.0.4
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libllvm8=8.0.1
  - libllvm9=9.0.1
  - libnetcdf=4.7.4
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libpq=12.2
  - libprotobuf=3.11.4
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - llvm-openmp=10.0.0
  - llvmlite=0.31.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mistune=0.8.4
  - mplcursors=0.3
  - munch=2.5.0
  - mysql-connector-c=6.1.11
  - mysql-connector-python=8.0.18
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.1
  - notebook=6.0.3
  - nspr=4.20
  - nss=3.47
  - numba=0.48.0
  - numpy=1.18.1
  - openjpeg=2.3.1
  - openssl=1.1.1f
  - pandas=1.0.3
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=12.2
  - proj=7.0.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - protobuf=3.11.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.0
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.8.2
  - python-dateutil=2.8.1
  - python-snappy=0.5.4
  - python_abi=3.8
  - pytz=2019.3
  - pyzmq=19.0.0
  - qt=5.12.5
  - qtconsole=4.7.3
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.23.0
  - rtree=0.9.4
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - shapely=1.7.0
  - six=1.14.0
  - snappy=1.1.8
  - sqlite=3.30.1
  - statsmodels=0.11.1
  - tbb=2018.0.5
  - terminado=0.8.3
  - testpath=0.4.4
  - thrift=0.11.0
  - tiledb=1.7.7
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - tzcode=2019a
  - urllib3=1.25.9
  - vincent=0.4.4
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xerces-c=3.2.2
  - xlrd=1.2.0
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - arcgis2geojson==2.0.0
    - cchardet==2.1.6
    - isoweek==1.3.3
    - networkx==2.4
    - partridge==1.1.1
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: /Users/edasmalchi/anaconda3/envs/pd1
